image: oven/bun:1.2

stages: [install, check, build]

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .bun/

install:
  stage: install
  script:
    - bun install --frozen-lockfile
  artifacts:
    paths:
      - node_modules/

check:
  stage: check
  script:
    - bun run check
  artifacts:
    when: always
    reports:
      junit: reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    paths:
      - coverage/

build:
  stage: build
  script: bun run build
  artifacts:
    paths:
      - dist
