export const ERRORS = {
    // Auth / access
    FORBIDDEN: 'FORBIDDEN',
    UNAUTHORIZED: 'UNAUTHORIZED',

    // Games
    TITLE_REQUIRED: 'TITLE_REQUIRED',
    RELEASE_YEAR_INVALID: 'RELEASE_YEAR_INVALID',
    GAME_TITLE_YEAR_ALREADY_EXISTS: 'GAME_TITLE_YEAR_ALREADY_EXISTS',
    GAME_NOT_FOUND: 'GAME_NOT_FOUND',

    // Library
    PLATFORM_REQUIRED: 'PLATFORM_REQUIRED',
    RATING_INVALID: 'RATING_INVALID',
    WANTS_TO_PLAY_INVALID: 'WANTS_TO_PLAY_INVALID',
    WANTS_TO_PLAY_MIN_INVALID: 'WANTS_TO_PLAY_MIN_INVALID',
    LIB_ENTRY_ALREADY_EXISTS: 'LIB_ENTRY_ALREADY_EXISTS',
    LIB_ENTRY_NOT_FOUND: 'LIB_ENTRY_NOT_FOUND',
} as const

export type ErrorCode = (typeof ERRORS)[keyof typeof ERRORS]
