name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.x'
      - name: Install
        run: bun install --frozen-lockfile
      - name: Check
        run: bun run check
      - name: Publish Unit Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: reports/junit.xml
      - name: Upload Coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage
      - name: Build
        run: bun run build
      - name: Upload dist
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
